# Generated by Django 5.0.6 on 2024-06-02 20:37

import django.db.models.deletion
import manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=manga.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('japanese_name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('manga_image', models.ImageField(blank=True, null=True, upload_to=manga.models.getFileName)),
                ('work_status', models.BooleanField(default=False, help_text='0-ongoing , 1-Completed')),
                ('tot_chapters', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show , 1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default , 1-trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.genre')),
            ],
        ),
    ]
