# Generated by Django 5.0.6 on 2024-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_genre_status_alter_mangas_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangas',
            name='files',
        ),
        migrations.AlterField(
            model_name='genre',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show , 1-Hidden'),
        ),
        migrations.AlterField(
            model_name='mangas',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show , 1-Hidden'),
        ),
        migrations.AlterField(
            model_name='mangas',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default , 1-trending'),
        ),
        migrations.AlterField(
            model_name='mangas',
            name='work_status',
            field=models.BooleanField(default=False, help_text='0-ongoing , 1-Completed'),
        ),
        migrations.DeleteModel(
            name='MangaFile',
        ),
    ]
