# Generated by Django 5.0.6 on 2024-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_remove_mangas_files_alter_genre_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
        migrations.AddField(
            model_name='mangas',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, to='manga.pdffile'),
        ),
    ]
