# Generated by Django 5.0.6 on 2024-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_pdffile_mangas_pdf_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='recommend',
            field=models.BooleanField(default=False, help_text='0-default , 1-recommend'),
        ),
    ]
