# Generated by Django 5.0.6 on 2024-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_mangas_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
