# Generated by Django 5.0.6 on 2024-06-04 16:06

import manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_genre_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=manga.models.getFileName),
        ),
    ]
