# Generated by Django 5.0.6 on 2024-06-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='manga_image',
        ),
        migrations.RemoveField(
            model_name='library',
            name='name',
        ),
    ]
