# Generated by Django 5.0.6 on 2024-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_alter_mangas_pdf_files_alter_pdffile_chapter_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='artist',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mangas',
            name='released_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
