# Generated by Django 5.0.6 on 2024-11-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0014_mangas_artist_mangas_released_date_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='adaption',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='mangas',
            name='color',
            field=models.CharField(choices=[('color', 'Color'), ('black_and_white', 'Black and White')], default='color', max_length=15),
        ),
    ]
