# Generated by Django 5.0.6 on 2024-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_mangas_adaption_mangas_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangas',
            name='adaption',
        ),
        migrations.AddField(
            model_name='mangas',
            name='anime_adaption',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
