# Generated by Django 5.0.6 on 2024-11-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0017_alter_mangas_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangas',
            old_name='anime_adaption',
            new_name='adaption',
        ),
    ]
