# Generated by Django 5.0.6 on 2024-11-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_chapterreadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterreadstatus',
            name='read_at',
        ),
    ]
